#!/bin/sh

set -e

lb config noauto                               \
    --architectures amd64                      \
    --linux-flavours amd64                     \
    --distribution jessie                      \
    --archive-areas "main contrib non-free"    \
    --bootappend-live "boot=live persistence"  \
    --linux-packages "linux-image"             \
    --clean                                    \
    --firmware-chroot true                     \
    --security true                            \
    "${@}"
