#!/bin/sh

set -e

lb config noauto                               \
    --architectures amd64                      \
    --linux-flavours amd64                     \
    --distribution stretch                     \
    --archive-areas "main contrib non-free"    \
    --bootappend-live "boot=live findiso=/images/stretch.iso"  \
    --clean                                    \
    --firmware-chroot true                     \
    --security true                            \
    "${@}"
